name: Trivy Scan

on:
  pull_request:

jobs:
  trivy-code-security-scan:
    runs-on: ubuntu-latest
    name: Trivy 
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Security Scan
        uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # 0.28.0
        with:
          scan-type: 'fs'
          scanners: vuln,secret
          exit-code: 1
          ignore-unfixed: true