name: Trivy Scan

on:
  pull_request:

jobs:
  trivy-code-security-scan:
    runs-on: ubuntu-latest
    name: Trivy 
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Security Scan
        uses: aquasecurity/trivy-action@a20de5420d57c4102486cdd9578b45609c99d7eb # 0.26.0
        with:
          scan-type: 'fs'
          scanners: vuln,secret
          exit-code: 1
          ignore-unfixed: true